
FD:
  POST_TRAIN:
    IS_USE: True
    NAME: basic
    OPTIMIZER: sgd
    OPTIMIZER_ARGS:
      MOMENTUM: 0.9
      WEIGHT_DECAY: 5e-4
    LOSS: categorical_crossentropy 
    SCHEDULER: cosineannealLR
    SCHEDULER_ARGS:
      T_MAX: 20
    BATCH_SIZE: 128
    EPOCHS: 20
    LR: 0.001
  
  METHOD:
    DECOMPOSITION: Tucker
    START_IDX: 6
    RANK: VBMF
    
