
FD:
  POST_TRAIN:
    IS_USE: True
    NAME: basic
    OPTIMIZER: sgd
    OPTIMIZER_ARGS:
      MOMENTUM: 0.9
      WEIGHT_DECAY: 5e-4
    LOSS: categorical_crossentropy # [categorical_crossentropy, kld, mae, mse] are available
    SCHEDULER: cosineannealLR # [stepLR, cosineannealLR, exponentialLR]
    SCHEDULER_ARGS:
      T_MAX: 50
    BATCH_SIZE: 128
    EPOCHS: 50
    LR: 0.001
  
  METHOD:
    DECOMPOSITION: Tucker
    START_IDX: 6
    RANK: VBMF
    
