
FD:
  POST_TRAIN:
    IS_USE: True
    NAME: basic
    OPTIMIZER: sgd
    OPTIMIZER_ARGS:
      MOMENTUM: 0.9
      WEIGHT_DECAY: 5e-4
    LOSS: categorical_crossentropy 
    SCHEDULER: cosineannealLR 
    SCHEDULER_ARGS:
      T_MAX: 50
    BATCH_SIZE: 128
    EPOCHS: 50
    LR: 0.001
  
  METHOD:
    DECOMPOSITION: Tucker
    START_IDX: 6
    RANK: VBMF

PRUNING:
  POST_TRAIN:
    IS_USE: True 
    NAME: basic 
    OPTIMIZER: sgd 
    OPTIMIZER_ARGS:  
      MOMENTUM: 0.9 
      WEIGHT_DECAY: 5e-4
    LOSS: categorical_crossentropy 
    SCHEDULER: cosineannealLR 
    SCHEDULER_ARGS:
      T_MAX: 100
    BATCH_SIZE: 256 
    EPOCHS: 100
    LR: 0.1

  METHOD:
    CRITERIA: EagleEye 
    CRITERIA_ARGS: 
      NUM_CANDIDATES: 20 
    STRATEGY: MinMaxStrategy
    STRATEGY_ARGS:
      PRUNING_RATIO: [0.0, 0.5] 


    
