PRUNING:
  POST_TRAIN:
    IS_USE: True
    OPTIMIZER: sgd
    LOSS: categorical_crossentropy # [categorical_crossentropy, kld, mae, mse] are available
    SCHEDULER: stepLR # [stepLR]
    BATCH_SIZE: 256
    EPOCHS: 30
    LR: 0.01
  
  STRATEGY:
    NAME: MinMaxStrategy
    PRUNING_RATIO: [0.0, 0.7]
  
  CRITERIA:
    NAME: L1Criteria
