PRUNING:
  POST_TRAIN:
    IS_USE: True 
    NAME: fskd 
    NUM_SAMPLES: 1000 
    LOSS: categorical_crossentropy 

  
  METHOD:
    CRITERIA: EagleEye 
    CRITERIA_ARGS: 
      NUM_CANDIDATES: 3 
    STRATEGY: MinMaxStrategy 
    STRATEGY_ARGS:
      PRUNING_RATIO: [0.0, 0.7]
