PRUNING:
  POST_TRAIN:
    IS_USE: True 
    NAME: basic
    OPTIMIZER: sgd 
    OPTIMIZER_ARGS:  
      MOMENTUM: 0.9
      WEIGHT_DECAY: 5e-4
    LOSS: categorical_crossentropy 
    SCHEDULER: stepLR 
    SCHEDULER_ARGS:
      STEP_SIZE: 30
      GAMMA: 0.1
    BATCH_SIZE: 256 
    EPOCHS: 80 
    LR: 0.01 

  METHOD:
    CRITERIA: EagleEye 
    CRITERIA_ARGS: 
      NUM_CANDIDATES: 10 
    STRATEGY: MinMaxStrategy 
    STRATEGY_ARGS:
      PRUNING_RATIO: [0.1, 0.6] 
