DATASET:
  NAME: cifar10
  IMG_SHAPE: [3, 32, 32] # C x H x W
  DATA_AUG: True


MODEL:
  NAME: resnet18
  NUM_CLASSES: 10
  PRE_TRAINED:
    IS_USE: False
    RETRAINED: False
    PATH: './saved_models/cifar10_vgg16_bn.pt'

TRAIN:
  OPTIMIZER: sgd # [sgd, adam] are available.
  LOSS: categorical_crossentropy # [categorical_crossentropy, kld, mae, mse] are available
  SCHEDULER: stepLR # [stepLR]
  BATCH_SIZE: 128
  EPOCHS: 140
  LR: 0.1

GPU:
  IS_USE: True
