DATASET:
  NAME: cifar10
  IMG_SHAPE: [3, 32, 32] 
  DATA_AUG: True

MODEL:
  NAME: densenet121
  NUM_CLASSES: 10
  PRE_TRAINED:
    IS_USE: False
    #PATH: './saved_models/origin_cifar10_vgg19_bn.pt'
    PATH: './saved_models/origin_cifar10_densenet121.pt'
  
TRAIN:
  IS_USE: True 
  OPTIMIZER: sgd
  OPTIMIZER_ARGS:
      MOMENTUM : 0.9
      WEIGHT_DECAY: 5e-4
  LOSS: categorical_crossentropy 
  SCHEDULER: stepLR 
  SCHEDULER_ARGS:
    STEP_SIZE: 60
    GAMMA: 0.1
  BATCH_SIZE: 128
  EPOCHS: 150
  LR: 0.1

GPU:
  IS_USE: True
